name: _
publish_to: none
environment:
  sdk: ^3.11.0

workspace:
  - flutter_mediapipe_vision
  - flutter_mediapipe_vision_android
  - flutter_mediapipe_vision_ios
  - flutter_mediapipe_vision_platform_interface
  - flutter_mediapipe_vision_web
